# Generated by Django 3.1.1 on 2020-12-08 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReadBook', '0002_auto_20201208_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_catagory',
            new_name='book_category',
        ),
    ]
