# Generated by Django 3.1.1 on 2020-12-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadBook', '0004_auto_20201209_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(default='default/no_cover.jpg', upload_to='book_images/'),
        ),
    ]
