# Generated by Django 3.1.1 on 2020-12-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadBook', '0006_auto_20201214_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(blank=True, default='default/no_cover.jpg', upload_to='book_images/'),
        ),
    ]
