# Generated by Django 3.1.1 on 2020-12-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadBook', '0007_auto_20201214_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='empty_cover',
            field=models.ImageField(null=True, upload_to='default/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(upload_to='book_images/'),
        ),
    ]
