# Generated by Django 3.1.1 on 2020-12-14 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReadBook', '0008_auto_20201214_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='empty_cover',
        ),
    ]
