# Generated by Django 3.1.1 on 2020-12-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadBook', '0009_remove_book_empty_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empty_cover', models.ImageField(null=True, upload_to='default/')),
            ],
        ),
    ]
