# Generated by Django 3.1.1 on 2020-12-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadBook', '0010_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(blank=True, upload_to='book_images/'),
        ),
    ]
